service: fad

frameworkVersion: ">=1.27.3 <2.0.0"

custom:
  fadTableName: ${self:service}-${self:provider.stage}
  fadTableArn:
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.fadTableName}
  fadTableIndexName: updated_at_idx
  fadTableIndexArn:
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.fadTableName}/index/*
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-python-requirements

# --stage prod --region us-east-2
provider:
  memorySize: 128
  name: aws
  region: us-west-2
  runtime: python3.6
  stage: dev
  timeout: 300

  environment:
    FAD_TABLE_NAME: ${self:custom.fadTableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:CreateBackup
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - ${self:custom.fadTableArn}
        - ${self:custom.fadTableIndexArn}

package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  process:
    name: ${self:custom.fadTableName}-process
    handler: manifest/process.handler
    events: ${file(./config/${self:provider.stage}.yml):process}
  # check:
  #   name: ${self:custom.fadTableName}-check
  #   handler: manifest/check.handler
  api:
    name: ${self:custom.fadTableName}-api
    handler: manifest/api.handler
    cors: true
    events:
      - http:
          path: "{site}/resources"
          method: get
          request:
            parameters:
              paths:
                site: true
  backup:
    name: ${self:custom.fadTableName}-backup
    handler: manifest/backup.handler
    events:
      - schedule:
          rate: cron(0 6 * * ? *)
          enabled: true

resources:
  Resources:
    FadTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.fadTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: site
            AttributeType: S
          - AttributeName: url
            AttributeType: S
          - AttributeName: updated_at
            AttributeType: N
        KeySchema:
          - AttributeName: site
            KeyType: HASH
          - AttributeName: url
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: ${self:custom.fadTableIndexName}
            KeySchema:
              - AttributeName: site
                KeyType: HASH
              - AttributeName: updated_at
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
