service: fad

frameworkVersion: ">=1.27.3 <2.0.0"

custom:
  fadTableName: ${self:service}-${self:provider.stage}
  fadTableArn:
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.fadTableName}
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-python-requirements

# --stage prod --region us-east-2
provider:
  memorySize: 128
  name: aws
  region: us-west-2
  runtime: python3.6
  stage: dev
  timeout: 300

  environment:
    FAD_TABLE_NAME: ${self:custom.fadTableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - ${self:custom.fadTableArn}

package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  process:
    name: ${self:custom.fadTableName}-process
    handler: manifest/process.handler
    events: ${file(./config/${self:provider.stage}.yml):fad}
  api:
    name: ${self:custom.fadTableName}-api
    handler: manifest/api.handler
    # events:
    #   - http:
    #       path: hello
    #       method: get

resources:
  Resources:
    FadTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.fadTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: site
            AttributeType: S
          - AttributeName: url
            AttributeType: S
          - AttributeName: updated_at
            AttributeType: N
        KeySchema:
          - AttributeName: site
            KeyType: HASH
          - AttributeName: url
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: updated_at_index
            KeySchema:
              - AttributeName: site
                KeyType: HASH
              - AttributeName: updated_at
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
