fad:
  - schedule:
      # every minute (dev only!)
      rate: cron(* * * * ? *)
      enabled: true
      input:
        site: demo
        location: https://archivesspace.lyrasistechnology.org/files/exports/manifest_ead_xml.csv
